name: Deploy Next.js to Azure Static Web Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build Next.js application
      - name: Build Next.js app
        run: npm run build

      # Step 5: Deploy to Azure Static Web App
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload" # Specify the action
          app_location: "/" # The root directory of your app
          output_location: ".next" # The location of the build output
          api_location: "" # Leave empty for no API
